# FLAG FOR PLOTS
VISUAL = True
# FLAG FOR COMMAND LINE PRINT AND PLOTS
COMMAND_LINE = True
# FLAG FOR WRITING INTO CSV
WRITE_CSV = False
# FLAG FOR WRITING INTO TSV
WRITE_TSV = False
# FLAG FOR PREDICT OVER ENTIRE EMBEDDINGS AFTER TRAIN ROUTINE
PREDICT = False

# AVAILABLE MODES
# USE_PRE_TRAINED: LOAD PREVIOUSLY SAVED MODELS, NO NEW TRAINING
# RESUME_TRAINING: LOAD PREVIOUSLY SAVED MODELS, AND RESUME TRAINING
# RESET_MODEL: RESTART TRAINING FROM SCRATCH
MODEL_MODE = 'USE_PRE_TRAINED'

# PARAMETERS
RAND_SEED = 123
N_EPOCHS = 100
BATCH_SIZE = 32
